services:
  angular:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/project





  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: python manage.py runserver 0.0.0.0:8000
