# Generated by Django 5.0.3 on 2024-04-15 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menu_category_category_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='menu',
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='menu.category'),
            preserve_default=False,
        ),
    ]
