# Generated by Django 5.0.3 on 2024-04-02 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_medio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CashBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Meu Caixa')),
                ('value_start', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_balance', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('date', models.DateField()),
                ('date_close', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_boxes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='financial.cashbox')),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.cashbox')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Fechado', 'Fechado')], max_length=10)),
                ('table', models.CharField(choices=[('Mesa 01', 'Mesa 01'), ('Mesa 02', 'Mesa 02')], max_length=10)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financial.cashbox')),
            ],
        ),
    ]
