# Generated by Django 4.2.7 on 2024-04-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
    ]
