# Generated by Django 4.2.7 on 2024-04-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_remove_transaction_canceled_alter_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='table',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type_order',
            field=models.CharField(choices=[('Mesa', 'Mesa'), ('Delivery', 'Delivey')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
