# Generated by Django 4.2.7 on 2024-04-24 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_category_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0005_remove_transaction_delivery_remove_transaction_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Receita', max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_PREPARO', 'Em preparo'), ('PRONTO', 'Pronto'), ('FECHADO', 'Fechado')], max_length=10)),
                ('type_order', models.CharField(choices=[('Mesa', 'Mesa'), ('Delivery', 'Delivey')], max_length=10)),
                ('open_timestamp', models.DateTimeField(blank=True, null=True)),
                ('preparation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('ready_timestamp', models.DateTimeField(blank=True, null=True)),
                ('closed_timestamp', models.DateTimeField(blank=True, null=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='financial.cashbox')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type_order',
        ),
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
