# Generated by Django 4.2.7 on 2024-04-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_orders_remove_transaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Em Preparo', 'Em preparo'), ('Pronto', 'Pronto'), ('Fechado', 'Fechado')], max_length=10),
        ),
    ]
