# Generated by Django 4.2.7 on 2024-04-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='amount',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
