# Generated by Django 4.2.7 on 2024-04-25 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0010_rename_amount_orders_total_remove_orders_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='menu_item',
        ),
    ]
