# Generated by Django 4.2.7 on 2024-04-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0011_remove_orders_menu_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='amount',
        ),
        migrations.AlterField(
            model_name='orders',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
