# Generated by Django 5.0.4 on 2024-05-03 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0014_methodpayments'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial.methodpayments'),
            preserve_default=False,
        ),
    ]
