# Generated by Django 5.0.4 on 2024-05-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0015_orders_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodpayments',
            name='type',
            field=models.CharField(choices=[('Pix', 'Pix'), ('Cash', 'Cash'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('VR', 'VR')], max_length=11),
        ),
    ]
