# Generated by Django 5.0.4 on 2024-05-03 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0017_alter_methodpayments_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodpayments',
            name='type',
            field=models.CharField(choices=[('Pix', 'Pix'), ('Cash', 'Cash'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('VR', 'VR')], max_length=11),
        ),
        migrations.AlterField(
            model_name='orders',
            name='payments',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial.methodpayments'),
        ),
    ]
