# Generated by Django 5.0.4 on 2024-05-03 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0018_alter_methodpayments_type_alter_orders_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial.methodpayments'),
        ),
    ]
