# Generated by Django 5.0.4 on 2024-05-03 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0020_remove_orders_payments_methodpayments_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methodpayments',
            name='order',
        ),
        migrations.AddField(
            model_name='orders',
            name='payments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial.methodpayments'),
        ),
        migrations.AlterField(
            model_name='methodpayments',
            name='type',
            field=models.CharField(choices=[('PIX', 'Pix'), ('CASH', 'Cash'), ('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card'), ('VR', 'VR')], max_length=11),
        ),
    ]
