# Generated by Django 5.0.4 on 2024-05-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0021_remove_methodpayments_order_orders_payments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payments',
        ),
        migrations.AddField(
            model_name='orders',
            name='type_payment',
            field=models.CharField(blank=True, choices=[('PIX', 'Pix'), ('CASH', 'Cash'), ('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card'), ('VR', 'VR')], max_length=11, null=True),
        ),
        migrations.DeleteModel(
            name='MethodPayments',
        ),
    ]
